FROM debian@sha256:9415ec02cf7f77ada7e0802545392477abe0fd9cd17b108b83d690f3c62571db

RUN groupadd -r testgroup && useradd -r testuser -G testgroup


COPY --chown=testuser:testgroup . /testroot

USER testuser

WORKDIR /testroot
RUN cat testfile
